# Generated by Django 4.2.29 on 2026-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_document_owner_alter_document_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='goals',
            field=models.TextField(blank=True),
        ),
    ]
