# Generated by Django 4.2.29 on 2026-03-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_chunk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunk',
            new_name='learning_ch_plan_id_cc7064_idx',
            old_name='learning_chunk_plan_doc_idx',
        ),
    ]
