# Generated by Codex on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
