# Generated by Codex on 2026-04-09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=24)),
                ('cardholder_name', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(max_length=64, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='users.user')),
            ],
            options={
                'db_table': 'users_payment_transaction',
                'ordering': ['-paid_at'],
            },
        ),
    ]
